### ISSUE TITLE
type constraint issue of scatter marker/line color

### ISSUE THREAD

**Issue by iynehz** [pablrod/p5-Chart-Plotly#21]
Now in latest Chart::Plotly they are `Maybe[ArrayRef]`, see
https://metacpan.org/source/PABLROD/Chart-Plotly-0.023/lib/Chart/Plotly/Trace/Scatter/Marker.pm#L70
https://metacpan.org/source/PABLROD/Chart-Plotly-0.023/lib/Chart/Plotly/Trace/Scatter/Marker/Line.pm#L66

But according to Plotly doc, it‘s `color or array of colors`
https://plot.ly/python/reference/#scatter-marker-color
https://plot.ly/python/reference/#scatter-marker-line-color

The issue also exists in Marker and Marker::Line of the Scattergl trace.

**Comment by pablrod** [comment]
Yes you're right! I'll try to fix this the next week

**Comment by pablrod** [comment]
After a small mistake with the release 0.024, it's fixed in 0.025!

https://metacpan.org/source/PABLROD/Chart-Plotly-0.025/lib/Chart/Plotly/Trace/Scatter/Marker.pm#L77

It's fixed also in Marker and Marker::Line of the Scattergl trace and also all the attributes that support color or an array of colors!

Please open a new issue if there is something I didn't fix!
